"""Hand-authored ground truth for the real Bagrut figures (written by a person from the PDF figure + question text).
Run once to (re)write manifests/*.json. NOT produced by any vision model."""
import json
from pathlib import Path

M = {
 "A01": dict(source="q14_p2_8.png", case="A01_qualitative", diagram_type="graph", subtype="qualitative_graph",
             required_labels=["(6 , a)", "(12 , 0)", "(18, −2a)"], critical_facts=[],
             required_values={"landmark_kinds": ["max", "x_intercept", "min"], "branches": 1, "horizontal_asymptotes": [0.0]},
             forbidden_objects=["formula"], expected="reconstruct"),
 "A02": dict(source="q16_p7_3.png", case="A02_formula_options", diagram_type="graph", subtype="multi_choice_graphs",
             required_labels=["I", "II", "III", "IV"], critical_facts=[], required_values={"options": ["I", "II", "III", "IV"]},
             forbidden_objects=["merged_options"], expected="reconstruct"),
 "A03": dict(source="q14_p3_4.png", case="A03_rational_options", diagram_type="graph", subtype="multi_choice_graphs",
             required_labels=["I", "II", "III", "IV"], critical_facts=[],
             required_values={"options": ["I", "II", "III", "IV"], "branches_per_option": [2, 2, 2, 2]},
             forbidden_objects=["merged_options"], expected="reconstruct"),
 "A04": dict(source="q14_p7_3.png", case="A04_formula_no_construction", diagram_type="graph", subtype="formula_graph",
             required_labels=[], critical_facts=["formula(f)=2sqrt(x^2-1)"], required_values={"roots": [-1.0, 1.0], "branches": 2},
             forbidden_objects=["point:A", "point:B"], expected="reconstruct"),
 "A05": dict(source="q16_p3_2.png", case="A05_scatter", diagram_type="chart", subtype="scatter_plot", required_labels=[],
             critical_facts=[], required_values={"scatter_points": [[5, 50], [10, 40], [15, 20], [15, 30], [20, 30], [25, 10]]},
             forbidden_objects=[], expected="reconstruct"),
 "A06": dict(source="q16_p8_2.png", case="A06_generic_plan", diagram_type="generic", subtype="schematic",
             required_labels=list("ABCDEFGHK"), critical_facts=[],
             required_values={"regions": ["גן פסלים", "מבואה", "שביל גישה"], "dimension": ["8 מטרים", ["A", "G"]],
                              "adjacency": [["גן פסלים", "שביל גישה"], ["מבואה", "שביל גישה"]]},
             forbidden_objects=[], expected="reconstruct"),
 "A07": dict(source="q18_p12_4.png", case="A07_table_haircuts", diagram_type="table", subtype="numeric_table", required_labels=[],
             critical_facts=[], required_values={"cells": [["סוג התספורת", "ילדים", "שיער קצר", "שיער ארוך", "מיוחדת"],
                                                           ["המחיר (בשקלים)", "60", "150", "180", "210"], ["מספר הלקוחות", "5", "21", "9", "10"]]},
             forbidden_objects=[], expected="reconstruct"),
 "A07b": dict(source="q19_p4_6.png", case="A07b_table_cakes", diagram_type="table", subtype="numeric_table", required_labels=[],
              critical_facts=[], required_values={"cells": [["סוג העוגה", "זמן הכנת התערובת (בדקות)", "זמן האפייה (בדקות)", "הרווח (בשקלים)"],
                                                            ["עוגת שוקולד", "4", "20", "47"], ["עוגת גבינה", "4", "60", "60"]]},
              forbidden_objects=[], expected="reconstruct"),
 "A08": dict(source="q16_p5_2.png", case="A08_coordinate_circle", diagram_type="geometry", subtype="analytic_geometry",
             required_labels=list("ABCDM"),
             critical_facts=["on_x_axis(M)", "coordinate(A)=-16,6", "coordinate(B)=0,18", "point_order(M,A,B)", "diameter(A,C)",
                             "tangent(A,D)", "on_y_axis(D)", "on_circle(A)", "on_circle(C)"],
             required_values={"coordinates": {"M": [-24, 0], "C": [-32, -6], "D": [0, -46 / 3]}}, forbidden_objects=[], expected="reconstruct"),
 "A09": dict(source="q15_p2_6.png", case="A09_box", diagram_type="spatial", subtype="cuboid",
             required_labels=["A", "A'", "B", "B'", "C", "C'", "D", "D'"], critical_facts=[],
             required_values={"edges": 12, "hidden_edges": [["A", "A'"], ["A", "B"], ["A", "D"]]}, forbidden_objects=[], expected="reconstruct"),
 "A09b": dict(source="q17_p3_2.png", case="A09b_pyramid_vectors", diagram_type="spatial", subtype="vector_box",
              required_labels=["A", "B", "C", "E", "F", "S"], critical_facts=["midpoint(E,B,S)", "ratio_on_segment(F,B,C)=0.6666666666666666"],
              required_values={"vectors": ["u", "v", "w"]}, forbidden_objects=[], expected="reconstruct"),
 "A10": dict(source="q15_p5_5.png", case="A10_log_options", diagram_type="graph", subtype="multi_choice_graphs",
             required_labels=["I", "II", "III", "IV"], critical_facts=[],
             required_values={"options": ["I", "II", "III", "IV"], "branches_per_option": [3, 3, 2, 1]}, forbidden_objects=["merged_options"],
             expected="reconstruct"),
 "A11": dict(source="q19_p8_4.png", case="A11_normal", diagram_type="chart", subtype="normal_distribution_schematic", required_labels=[],
             critical_facts=[], required_values={"percentages": ["0.5%", "1.5%", "5%", "9%", "15%", "19%", "19%", "15%", "9%", "5%", "1.5%", "0.5%"],
                                                 "answer_boxes": 11}, forbidden_objects=[], expected="reconstruct"),
 "A12": dict(source="q19_p12_2.png", case="A12_voxel", diagram_type="spatial", subtype="voxel_structure", required_labels=[],
             critical_facts=[], required_values={}, forbidden_objects=[], expected="safe_fallback",
             note="hidden columns cannot be read from the image: the only correct outcome is the original image"),
 "A13": dict(source="q19_p14_2.png", case="A13_carton_cup", diagram_type="spatial", subtype="cylinder_in_box", required_labels=[],
             critical_facts=["dimension=height:24", "dimension=width:6.5", "dimension=radius:3"],
             required_values={"dimensions": [["carton", "height", 24], ["carton", "width", 6.5], ["carton", "depth", 6.5], ["cup", "radius", 3]]},
             forbidden_objects=["dimension:cup:diameter"], expected="reconstruct"),
 "A14": dict(source="q14_p5_2.png", case="A14_circle_kite", diagram_type="geometry", subtype="circle_geometry",
             required_labels=list("ABCEKMO"),
             critical_facts=["diameter(A,B)", "on_circle(C)", "intersection(K,A,M,C,O)", "point_on_segment(E,B,O)",
                             "equal_length(M,K,M,E)", "equal_length(O,K,O,E)", "point_order(A,O,E,B)"],
             required_values={}, forbidden_objects=[], expected="reconstruct"),
}
out = Path(__file__).parent / "manifests"
for k, v in M.items():
    (out / f"{k}_expected.json").write_text(json.dumps({"id": k, **v}, ensure_ascii=False, indent=2), encoding="utf-8")
print(len(M), "manifests written")
